---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kubeflow-instance
  namespace: ${releaseNamespace}
spec:
  interval: 1m0s
  ref:
    tag: v1.8.1
  timeout: 15m0s
  url: https://github.com/WinsonSou/llm-on-ntnx